### ISSUE TITLE
docker compose up doesn't use credentials to pull images from ghcr.io

### ISSUE THREAD

**Issue by Zenexer** [docker/compose-cli#1545]
**Description**

Attempting to run `docker compose up -d` with a compose file that references a private image on ghcr.io fails with the following error:

> failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized

`docker-compose up -d` works, and `docker compose up -d` works if I run `docker pull` for that image first.

**Steps to reproduce the issue:**

1. Create a docker-compose.yml file that references a private image on ghcr.io
2. Log into ghcr.io via `docker login ghcr.io`
3. Run `docker compose up -d`

**Describe the results you received:**

```
% docker --debug compose up -d
DEBUG serving grpc connection
DEBUG serving grpc connection
DEBUG serving grpc connection
[+] Building 0.7s (7/7)
 => [redacted1 internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 86B 0.0s
[+] Building 0.8s (9/9) FINISHED
 => [redacted1 internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 86B 0.0s
 => [elasticsearch internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 62B 0.0s
 => [phpmyadmin internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 69B 0.0s
 => [redacted1 internal] load .dockerignore 0.0s
 => => transferring context: 2B 0.0s
 => [elasticsearch internal] load .dockerignore 0.0s
 => => transferring context: 2B 0.0s
 => [phpmyadmin internal] load .dockerignore 0.0s
 => => transferring context: 2B 0.0s
 => ERROR [redacted1 internal] load metadata for ghcr.io/redacted2/redacted3:redacted4 0.1s
 => CANCELED [elasticsearch internal] load metadata for docker.io/library/elasticsearch:7.12.0 0.0s
 => CANCELED [phpmyadmin internal] load metadata for docker.io/library/phpmyadmin:5.1.0-fpm-alpine 0.0s
------
 > [redacted1 internal] load metadata for ghcr.io/redacted2/redacted3:redacted4:
------
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Describe the results you expected:**

Same behavior as `docker-compose up -d`: compose-cli should use the credentials received from `docker login`

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm on the M1 preview build of Docker Desktop for macOS, 3.3.0 (62632), RC3.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.10
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  

```
% docker context show
default
% docker context inspect default
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: MTTL:GPGI:RRKW:ACCC:BZVR:CAEG:SYFI:WGRP:45J2:QISG:IXDQ:RSK4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

I'm on the M1 preview build of Docker Desktop for macOS, 3.3.0 (62632), RC3

**Comment by ndeloof** [comment]
This should have been fixed already by https://github.com/docker/compose-cli/commit/26b8ef0f498c6c3fafbab4e6fc2b8ada3222d915

**Comment by Zenexer** [comment]
@ndeloof I can confirm that it's still not fixed in the stable release of Docker Desktop for M1 that came out yesterday: 3.3.1 (63152).  Updated `docker version` output:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mdi** [comment]
I'm seeing the same issue with the same version as @Zenexer.

**Comment by Zenexer** [comment]
@mdi Yeah, 1.0.13 hasn't shipped with Docker Desktop for macOS yet.  Hopefully it'll be included in the next release.

**Comment by Zenexer** [comment]
@ndeloof I'm now on 1.0.14, but the issue still exists, so I don't think it was fixed by 26b8ef0f498c6c3fafbab4e6fc2b8ada3222d915.

**Comment by ndeloof** [comment]
It seems this issue is specific to github package registry.

I pushed a test image to give it a try, the deleted from my workstation and pulled:
```
➜  docker pull  docker.pkg.github.com/ndeloof/bidule/alpine:latest
WARNING: ⚠️ Failed to pull manifest by the resolved digest. This registry does not
	appear to conform to the distribution registry specification; falling back to
	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
	release.  Please contact admins of https://docker.pkg.github.com. ⚠️

latest: Pulling from ndeloof/bidule/alpine
Digest: sha256:2993cc6bd8b2db7dd2fba56efe7c1181640395d171fd8c1c1e83440440379ffb
Status: Downloaded newer image for docker.pkg.github.com/ndeloof/bidule/alpine:latest
docker.pkg.github.com/ndeloof/bidule/alpine:latest
```

When using this as a base image and rely on BuildKit to build, I get a failure:
```
➜  docker build .
[+] Building 1.0s (4/4) FINISHED                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 36B                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => ERROR [internal] load metadata for docker.pkg.github.com/ndeloof/bidule/alpine:latest                                                                               0.8s
 => [auth] sharing credentials for docker.pkg.github.com                                                                                                                0.0s
------
 > [internal] load metadata for docker.pkg.github.com/ndeloof/bidule/alpine:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to copy: httpReadSeeker: failed open: content at https://docker.pkg.github.com/v2/ndeloof/bidule/alpine/manifests/sha256:2993cc6bd8b2db7dd2fba56efe7c1181640395d171fd8c1c1e83440440379ffb not found: not found
```

As `docker compose` relies on BuildKit same error appears running `docker compose ..` commands.

**Comment by ndeloof** [comment]
Also tested enabling github new container repository, and have a different behaviour:
`docker build .` when using `FROM  ghcr.io/ndeloof/bidule:1.0` SUCCEED
`docker compose up` when using `ghcr.io/ndeloof/bidule:1.0` as service image FAILS

investigating ...

**Comment by tanettrimas** [comment]
I have the same issue when we need credentials from aws to pull a docker image. 
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 401 Unauthorized

Using docker-compose instead works.

**Comment by ndeloof** [comment]
This has been fixed by #1651

**Comment by tanettrimas** [comment]
@ndeloof Is this fix pushed to the newest version of docker? I still getting an error trying it. 

 => ERROR [internal] load metadata for <some repo>
------
 > [internal] load metadata for <some repo>------
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 401 Unauthorized

**Comment by tanettrimas** [comment]
Or rather - when will next release be? :D

**Comment by ndeloof** [comment]
we are publishing a release today

**Comment by aripollak** [comment]
I'm still getting this error on Docker Desktop for Mac 3.4.0 (which seems like should include the fix in #1651) when trying to build an image based on one hosted privately on Docker Hub. Is it possible that fix didn't work?

**Comment by ndeloof** [comment]
This fix only added support for private image pull, not build FROM private images :'(
https://github.com/docker/compose-cli/commit/fe085df7b7692deee9464989dbe7470062cf7e7c is the fix you need, not yet released

**Comment by boing102** [comment]
Manually downgrading to v3.3.2 solved the issue until the fix is in place

**Comment by andreygolev** [comment]
и у меня всё так же ((

**Comment by HagayRatzabi** [comment]
Is this one released allready?

> This fix only added support for private image pull, not build FROM private images :'(
> [fe085df](https://github.com/docker/compose-cli/commit/fe085df7b7692deee9464989dbe7470062cf7e7c) is the fix you need, not yet released

Is this one released?

**Comment by ascendantlogic** [comment]
Can confirm that `docker compose build` is still failing when pulling from a private ECR repo that is logged in to but `docker-compose build` works properly.
